### PR TITLE
Fix git ssh user

### PR DESCRIPTION
**Pull request by boxboatmatt**
Signed-off-by: Matthew DeVenny <matt@boxboat.com>

Add user 1000 and set DefaultMode to 0600 for GitClientSecret on tekton job

https://github.com/rancher/fleet/issues/216

### CODE REVIEW

**Review by dramich — COMMENTED** [review]
@boxboatmatt Can you split this into two commits at least (I would prefer two PRs) one for the real change and another for the date change.

**Comment by boxboatmatt** [comment]
@dramich https://github.com/rancher/gitjob/pull/27
will update this PR

**Comment by StrongMonkey** [comment]
@boxboatmatt I am putting this https://github.com/rancher/gitjob/pull/28 to address the issue though. The secret mode won't fix it though. see https://github.com/tektoncd/pipeline/issues/3509#issuecomment-756974715

**Comment by boxboatmatt** [comment]
@StrongMonkey alrighty... you sure you don't also need to set the secret volume permissions? The private ssh key needs to be `0400`

**Comment by StrongMonkey** [comment]
@boxboatmatt From what I tested it looks fine. Tekton code actually copied these files with 0600 permission. https://github.com/tektoncd/pipeline/blob/f112277e99c6805ed780a297c6a99b0827f0164d/pkg/credentials/gitcreds/ssh.go#L139

**Comment by StrongMonkey** [comment]
included in https://github.com/rancher/gitjob/pull/28

**Pull request closed without merging**
