### PR TITLE
Use debugger-friendly compile settings if DEBUG is set

### PR DESCRIPTION
**Pull request by moio**
This is the equivalent PR of https://github.com/rancher/fleet/pull/961

Please refer to the PR above for all details.

### CODE REVIEW

**Comment by mattfarina** [comment]
@moio can you rebase this PR so that all tests can be handled appropriately. Fixed the failing test on PR issue you experienced.

**Comment by moio** [comment]
Rebased, checks green!

**Comment by moio** [comment]
Is there anything else I should do to have this merged?

**Review by thardeck — APPROVED** [review]

**Comment by moio** [comment]
Thanks!

**Pull request merged**
